# Generated by Django 4.2.17 on 2025-04-21 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('KATA_INDIVIDUAL', 'Individual Kata'), ('KATA_TEAM', 'Team Kata'), ('KUMITE_INDIVIDUAL', 'Individual Kumite'), ('KUMITE_TEAM', 'Team Kumite')], max_length=20)),
                ('age_category', models.CharField(choices=[('CADET', '14-15 years'), ('JUNIOR', '16-17 years'), ('SENIOR', '18+ years')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight_category', models.CharField(blank=True, choices=[('-55KG', 'Under 55kg'), ('-60KG', 'Under 60kg'), ('-67KG', 'Under 67kg'), ('-75KG', 'Under 75kg'), ('-84KG', 'Under 84kg'), ('+84KG', 'Over 84kg'), ('-50KG', 'Under 50kg'), ('-55KG', 'Under 55kg'), ('-61KG', 'Under 61kg'), ('-68KG', 'Under 68kg'), ('+68KG', 'Over 68kg')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('belt_rank', models.CharField(choices=[('9KYU', '9th Kyu - White Belt'), ('8KYU', '8th Kyu - Yellow Belt'), ('7KYU', '7th Kyu - Orange Belt'), ('6KYU', '6th Kyu - Green Belt'), ('5KYU', '5th Kyu - Blue Belt'), ('4KYU', '4th Kyu - Purple Belt'), ('3KYU', '3rd Kyu - Brown Belt'), ('2KYU', '2nd Kyu - Brown Belt'), ('1KYU', '1st Kyu - Brown Belt'), ('1DAN', '1st Dan - Black Belt'), ('2DAN', '2nd Dan - Black Belt'), ('3DAN', '3rd Dan - Black Belt'), ('4DAN', '4th Dan - Black Belt'), ('5DAN', '5th Dan - Black Belt')], max_length=5)),
                ('club', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_team_event', models.BooleanField(default=False)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(related_name='participants', to='core.event')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('match_number', models.PositiveIntegerField()),
                ('score1', models.PositiveIntegerField(blank=True, null=True)),
                ('score2', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_competitor1', to='core.participant')),
                ('competitor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_competitor2', to='core.participant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_won', to='core.participant')),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
                'unique_together': {('event', 'round_number', 'match_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('tournament', 'category', 'age_category', 'gender', 'weight_category')},
        ),
    ]
