# Generated by Django 5.2 on 2025-05-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_category',
            field=models.CharField(choices=[('CADET', '14-15 years'), ('JUNIOR', '16-17 years'), ('U21', '18-20 years'), ('SENIOR', '18+ years')], max_length=10),
        ),
    ]
