# Generated by Django 4.2.7 on 2025-05-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='belt_rank',
            field=models.CharField(choices=[('NIL', 'Not Applicable'), ('9KYU', '9th Kyu - White Belt'), ('8KYU', '8th Kyu - Yellow Belt'), ('7KYU', '7th Kyu - Orange Belt'), ('6KYU', '6th Kyu - Green Belt'), ('5KYU', '5th Kyu - Blue Belt'), ('4KYU', '4th Kyu - Purple Belt'), ('3KYU', '3rd Kyu - Brown Belt'), ('2KYU', '2nd Kyu - Brown Belt'), ('1KYU', '1st Kyu - Brown Belt'), ('1DAN', '1st Dan - Black Belt'), ('2DAN', '2nd Dan - Black Belt'), ('3DAN', '3rd Dan - Black Belt'), ('4DAN', '4th Dan - Black Belt'), ('5DAN', '5th Dan - Black Belt')], max_length=5),
        ),
    ]
